# Generated by Django 6.0.4 on 2026-08-31 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_date', models.DateField()),
                ('predicted_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('model_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demand Forecast',
                'verbose_name_plural': 'Demand Forecasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETAProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_arrival', models.DateTimeField()),
                ('confidence_low', models.DateTimeField()),
                ('confidence_high', models.DateTimeField()),
                ('model_version', models.CharField(max_length=50)),
                ('factors', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ETA Projection',
                'verbose_name_plural': 'ETA Projections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggested_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True, default='')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pricing Recommendation',
                'verbose_name_plural': 'Pricing Recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggested_route', models.JSONField(blank=True, default=dict)),
                ('estimated_savings_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_savings_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fuel_savings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_applied', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Route Optimization',
                'verbose_name_plural': 'Route Optimizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(choices=[('speed', 'Speed Anomaly'), ('deviation', 'Route Deviation'), ('unauthorized', 'Unauthorized Use'), ('dwell', 'Excessive Dwell')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_anomalies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anomaly Detection',
                'verbose_name_plural': 'Anomaly Detections',
                'ordering': ['-detected_at'],
            },
        ),
    ]
