# Generated by Django 6.0.4 on 2026-08-31 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_intelligence', '0001_initial'),
        ('cargo', '0001_initial'),
        ('gps_tracking', '0001_initial'),
        ('transportation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalydetection',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='gps_tracking.gpsdevice'),
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='transportation.route'),
        ),
        migrations.AddField(
            model_name='etaprojection',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eta_projections', to='cargo.shipment'),
        ),
        migrations.AddField(
            model_name='pricingrecommendation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pricing_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingrecommendation',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_recommendations', to='transportation.route'),
        ),
        migrations.AddField(
            model_name='routeoptimization',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_optimizations', to='transportation.trip'),
        ),
    ]
