# Generated by Django 6.0.4 on 2026-08-31 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverScorecard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('speeding_events', models.PositiveIntegerField(default=0)),
                ('harsh_braking_events', models.PositiveIntegerField(default=0)),
                ('on_time_deliveries', models.PositiveIntegerField(default=0)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('avg_speed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_speed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_consumed_l', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Driver Scorecard',
                'verbose_name_plural': 'Driver Scorecards',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('odometer_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=8)),
                ('station', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fuel Log',
                'verbose_name_plural': 'Fuel Logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('corrective', 'Corrective'), ('emergency', 'Emergency')], max_length=12)),
                ('description', models.TextField()),
                ('mileage_at_service', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_service_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('performed_by', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='scheduled', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehicle Maintenance',
                'verbose_name_plural': 'Vehicle Maintenance Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarbonEmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_consumed_l', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emission_factor', models.DecimalField(decimal_places=4, max_digits=8)),
                ('total_emissions_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_emissions', to='cargo.shipment')),
            ],
            options={
                'verbose_name': 'Carbon Emission',
                'verbose_name_plural': 'Carbon Emissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
