# Generated by Django 6.0.4 on 2026-08-31 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet_intelligence', '0001_initial'),
        ('transportation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonemission',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_emissions', to='transportation.trip'),
        ),
        migrations.AddField(
            model_name='carbonemission',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_emissions', to='transportation.vehicle'),
        ),
        migrations.AddField(
            model_name='driverscorecard',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='transportation.driver'),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='transportation.vehicle'),
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='transportation.vehicle'),
        ),
    ]
