# Generated by Django 6.0.4 on 2026-08-31 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gps_tracking', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hs_code', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_number', models.CharField(max_length=30, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('qr_code', models.CharField(blank=True, max_length=255)),
                ('package_type', models.CharField(choices=[('box', 'Box'), ('crate', 'Crate'), ('pallet', 'Pallet'), ('bag', 'Bag'), ('drum', 'Drum'), ('container', 'Container'), ('envelope', 'Envelope'), ('other', 'Other')], default='box', max_length=15)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, default=0, help_text='cm', max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, default=0, help_text='cm', max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, default=0, help_text='cm', max_digits=8)),
                ('volume', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('in_warehouse', 'In Warehouse'), ('sorted', 'Sorted'), ('loaded', 'Loaded'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_gps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_packages', to='gps_tracking.gpsdevice')),
            ],
            options={
                'ordering': ['package_number'],
            },
        ),
    ]
