# Generated by Django 6.0.4 on 2026-08-31 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0003_initial'),
        ('packages', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='current_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='warehouse.warehousebin'),
        ),
        migrations.AddField(
            model_name='package',
            name='current_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='package',
            name='current_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='warehouse.warehousezone'),
        ),
        migrations.AddField(
            model_name='package',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='cargo.shipment'),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packages.package'),
        ),
    ]
