# Generated by Django 6.0.4 on 2026-08-31 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorderCrossingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('documents_checked', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Border Crossing Event',
                'verbose_name_plural': 'Border Crossing Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BorderPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('expected_dwell_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Border Post',
                'verbose_name_plural': 'Border Posts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CorridorRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corridor_name', models.CharField(max_length=200)),
                ('corridor_type', models.CharField(choices=[('central', 'Central Corridor'), ('southern', 'Southern Corridor'), ('northern', 'Northern Corridor')], max_length=10)),
                ('countries', models.JSONField(blank=True, default=list)),
                ('is_treaty_route', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Corridor Route',
                'verbose_name_plural': 'Corridor Routes',
                'ordering': ['corridor_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomsDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('declaration_number', models.CharField(max_length=100, unique=True)),
                ('hs_code', models.CharField(max_length=20)),
                ('goods_description', models.TextField()),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('duty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customs Declaration',
                'verbose_name_plural': 'Customs Declarations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegionalAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('assigned_shipments', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Regional Agent',
                'verbose_name_plural': 'Regional Agents',
                'ordering': ['name'],
            },
        ),
    ]
