# Generated by Django 6.0.4 on 2026-08-31 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        ('cross_border', '0001_initial'),
        ('gps_tracking', '0001_initial'),
        ('saas_config', '0001_initial'),
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordercrossingevent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='border_crossing_events', to='gps_tracking.gpsdevice'),
        ),
        migrations.AddField(
            model_name='bordercrossingevent',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='border_crossing_events', to='cargo.shipment'),
        ),
        migrations.AddField(
            model_name='bordercrossingevent',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='border_crossing_events', to='transportation.trip'),
        ),
        migrations.AddField(
            model_name='borderpost',
            name='geofence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='border_posts', to='gps_tracking.geofence'),
        ),
        migrations.AddField(
            model_name='bordercrossingevent',
            name='border_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossing_events', to='cross_border.borderpost'),
        ),
        migrations.AddField(
            model_name='corridorroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridor_routes', to='transportation.route'),
        ),
        migrations.AddField(
            model_name='customsdeclaration',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customs_declarations', to='cargo.shipment'),
        ),
        migrations.AddField(
            model_name='regionalagent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_agents', to='saas_config.organization'),
        ),
    ]
