# Generated by Django 6.0.4 on 2026-08-31 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('daily_cargo', 'Daily Cargo Report'), ('monthly_cargo', 'Monthly Cargo Report'), ('revenue', 'Revenue Report'), ('outstanding_balances', 'Outstanding Balances'), ('branch_performance', 'Branch Performance'), ('destination_analysis', 'Destination Analysis'), ('delivery_performance', 'Delivery Performance'), ('delayed_shipments', 'Delayed Shipments'), ('lost_damaged', 'Lost & Damaged'), ('warehouse_utilization', 'Warehouse Utilization'), ('vehicle_utilization', 'Vehicle Utilization'), ('driver_performance', 'Driver Performance'), ('gps_history', 'GPS History'), ('payment_reconciliation', 'Payment Reconciliation'), ('customer_statement', 'Customer Statement'), ('audit_report', 'Audit Report')], max_length=30)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='saas_config.organization')),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('daily_cargo', 'Daily Cargo Report'), ('monthly_cargo', 'Monthly Cargo Report'), ('revenue', 'Revenue Report'), ('outstanding_balances', 'Outstanding Balances'), ('branch_performance', 'Branch Performance'), ('destination_analysis', 'Destination Analysis'), ('delivery_performance', 'Delivery Performance'), ('delayed_shipments', 'Delayed Shipments'), ('lost_damaged', 'Lost & Damaged'), ('warehouse_utilization', 'Warehouse Utilization'), ('vehicle_utilization', 'Vehicle Utilization'), ('driver_performance', 'Driver Performance'), ('gps_history', 'GPS History'), ('payment_reconciliation', 'Payment Reconciliation'), ('customer_statement', 'Customer Statement'), ('audit_report', 'Audit Report')], max_length=30)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Report Export',
                'verbose_name_plural': 'Report Exports',
                'ordering': ['-created_at'],
            },
        ),
    ]
