# Generated by Django 6.0.4 on 2026-08-31 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        ('saas_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('speed', 'Speed Exceeded'), ('offline', 'Device Offline'), ('low_battery', 'Low Battery'), ('geofence', 'Geofence Event'), ('deviation', 'Route Deviation'), ('unauthorized', 'Unauthorized Movement')], max_length=15)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('message', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GPSDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracker_id', models.CharField(max_length=50, unique=True)),
                ('imei', models.CharField(max_length=20, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('device_type', models.CharField(choices=[('vehicle', 'Vehicle Tracker'), ('cargo', 'Cargo Tracker'), ('portable', 'Portable')], default='vehicle', max_length=10)),
                ('sim_number', models.CharField(blank=True, max_length=20)),
                ('network_provider', models.CharField(blank=True, max_length=50)),
                ('battery_level', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='offline', max_length=15)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_speed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_heading', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_altitude', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='GPSDeviceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('cargo', 'Cargo'), ('package', 'Package')], max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='GPSPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('heading', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('altitude', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('battery_level', models.PositiveIntegerField(blank=True, null=True)),
                ('ignition', models.BooleanField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fence_type', models.CharField(choices=[('branch', 'Branch'), ('warehouse', 'Warehouse'), ('port', 'Port'), ('airport', 'Airport'), ('border', 'Border Post'), ('delivery_area', 'Delivery Area'), ('custom', 'Custom')], default='custom', max_length=15)),
                ('shape', models.CharField(choices=[('circle', 'Circle'), ('polygon', 'Polygon')], default='circle', max_length=10)),
                ('center_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('center_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_meters', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('polygon_coords', models.JSONField(blank=True, default=list, help_text='List of [lat,lng] pairs')),
                ('is_active', models.BooleanField(default=True)),
                ('alert_on_enter', models.BooleanField(default=True)),
                ('alert_on_exit', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='saas_config.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('enter', 'Enter'), ('exit', 'Exit')], max_length=5)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='gps_tracking.geofence')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofence_events', to='cargo.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
