# Generated by Django 6.0.4 on 2026-08-31 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0003_initial'),
        ('gps_tracking', '0002_initial'),
        ('packages', '0001_initial'),
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdeviceassignment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.package'),
        ),
        migrations.AddField(
            model_name='gpsdeviceassignment',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargo.shipment'),
        ),
        migrations.AddField(
            model_name='gpsdeviceassignment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transportation.vehicle'),
        ),
        migrations.AddField(
            model_name='gpsposition',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='gps_tracking.gpsdevice'),
        ),
        migrations.AddIndex(
            model_name='gpsposition',
            index=models.Index(fields=['device', 'timestamp'], name='gps_trackin_device__28967c_idx'),
        ),
    ]
