# Generated by Django 6.0.4 on 2026-08-31 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('subdomain', models.CharField(blank=True, default='', max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='organizations/logos/')),
                ('favicon', models.ImageField(blank=True, upload_to='organizations/favicons/')),
                ('primary_color', models.CharField(default='#D96A16', max_length=7)),
                ('secondary_color', models.CharField(default='#38AEF2', max_length=7)),
                ('accent_color', models.CharField(default='#6D5BD0', max_length=7)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('timezone', models.CharField(default='Africa/Dar_es_Salaam', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('enterprise', 'Enterprise')], default='free', max_length=10)),
                ('max_users', models.PositiveIntegerField(blank=True, null=True)),
                ('max_shipments', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='saas_config.organization')),
            ],
            options={
                'verbose_name': 'Organization Domain',
                'verbose_name_plural': 'Organization Domains',
                'ordering': ['-is_primary', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='TenantQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('users_used', models.PositiveIntegerField(default=0)),
                ('shipments_used', models.PositiveIntegerField(default=0)),
                ('storage_used_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('api_requests_used', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='saas_config.organization')),
            ],
            options={
                'verbose_name': 'Tenant Quota',
                'verbose_name_plural': 'Tenant Quotas',
            },
        ),
    ]
