# Generated by Django 6.0.4 on 2026-08-31 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0003_initial'),
        ('iot_sensors', '0001_initial'),
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalseal',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_seals', to='packages.package'),
        ),
        migrations.AddField(
            model_name='digitalseal',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_seals', to='cargo.shipment'),
        ),
        migrations.AddField(
            model_name='digitalseal',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_digital_seals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sensoralert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_sensor_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sensordevice',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_devices', to='packages.package'),
        ),
        migrations.AddField(
            model_name='sensordevice',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_devices', to='cargo.shipment'),
        ),
        migrations.AddField(
            model_name='sensoralert',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='iot_sensors.sensordevice'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='iot_sensors.sensordevice'),
        ),
    ]
