# Generated by Django 6.0.4 on 2026-08-31 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('booking_number', models.CharField(max_length=30, unique=True)),
                ('waybill_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_phone', models.CharField(max_length=20)),
                ('sender_address', models.TextField(blank=True)),
                ('sender_city', models.CharField(blank=True, max_length=100)),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('receiver_address', models.TextField(blank=True)),
                ('receiver_city', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('cargo_type', models.CharField(choices=[('general', 'General Cargo'), ('perishable', 'Perishable'), ('hazardous', 'Hazardous'), ('fragile', 'Fragile'), ('oversized', 'Oversized'), ('liquid', 'Liquid'), ('electronics', 'Electronics'), ('textiles', 'Textiles'), ('mining', 'Mining Equipment'), ('agriculture', 'Agricultural'), ('pharmaceutical', 'Pharmaceutical')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('num_packages', models.PositiveIntegerField(default=1)),
                ('actual_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volumetric_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('charged_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, default=0, help_text='cm', max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, default=0, help_text='cm', max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, default=0, help_text='cm', max_digits=8)),
                ('declared_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_insured', models.BooleanField(default=False)),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pickup_required', models.BooleanField(default=False)),
                ('delivery_required', models.BooleanField(default=True)),
                ('special_handling', models.TextField(blank=True)),
                ('is_fragile', models.BooleanField(default=False)),
                ('is_perishable', models.BooleanField(default=False)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('awaiting_receiving', 'Awaiting Receiving'), ('received', 'Received'), ('in_warehouse', 'In Warehouse'), ('sorted', 'Sorted'), ('ready_for_dispatch', 'Ready for Dispatch'), ('loaded', 'Loaded'), ('in_transit', 'In Transit'), ('arrived_destination', 'Arrived Destination'), ('customs_hold', 'Customs Hold'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivery_attempted', 'Delivery Attempted'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('cancelled', 'Cancelled')], db_index=True, default='booked', max_length=25)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overpaid', 'Overpaid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estimated_departure', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('handling_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qr_code', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('public_tracking_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=25)),
                ('new_status', models.CharField(max_length=25)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('gps', 'GPS'), ('scanner', 'Scanner'), ('api', 'API'), ('automation', 'Automation')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargoAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('driver', 'Driver'), ('gps', 'GPS Device'), ('trip', 'Trip'), ('warehouse', 'Warehouse')], max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargoEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('status_change', 'Status Change'), ('location_update', 'Location Update'), ('assignment', 'Assignment'), ('note', 'Note'), ('scan', 'Scan'), ('exception', 'Exception')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargoNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
