# Generated by Django 6.0.4 on 2026-08-31 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('cargo', '0001_initial'),
        ('gps_tracking', '0001_initial'),
        ('transportation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='transportation.driver'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='assigned_gps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_shipments', to='gps_tracking.gpsdevice'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='assigned_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='transportation.trip'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='transportation.vehicle'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_cargo', to='branches.branch'),
        ),
    ]
